apiVersion: v1
kind: Pod
metadata:
  name: cfs-communication-pod
  labels:
    app: cfs-demo
spec:
  containers:
  - name: cfs-container
    image: cfs:latest
    ports:
    - containerPort: 1234
      protocol: UDP
    env:
    - name: DUMMY_CONTAINER_IP
      value: "REPLACE_WITH_DUMMY_IP"  # This should be replaced with actual IP
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    imagePullPolicy: Never
  - name: dummy-container
    image: dummy:latest
    ports:
    - containerPort: 9002
      protocol: UDP
    env:
    - name: CFS_CONTAINER_IP
      value: "REPLACE_WITH_CFS_IP"    # This should be replaced with actual IP
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    imagePullPolicy: Never
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cfs-service
spec:
  selector:
    app: cfs-demo
  ports:
  - name: cfs-udp
    port: 1234
    targetPort: 1234
    protocol: UDP
  - name: dummy-udp
    port: 9002
    targetPort: 9002
    protocol: UDP
  type: NodePort